### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by peraslaksen** [bast/tms-location#5] opened 2024-06-07 08:00 UTC
Error on another computer when using the tms-location.sif : input data are txt files (mesh data) from extract-surfaces.sif 

./tms-location.sif /home/per/tms_nav/out
Traceback (most recent call last):
  File "/software/app.py", line 82, in <module>
    surface_files = get_list_of_files(args.input_directory)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/app.py", line 32, in get_list_of_files
    surface_files.remove("outside-only.txt")
ValueError: list.remove(x): x not in list

**Comment by bast** [comment] 2024-06-14 08:14
Does the data directory contain the file `outside-only.txt`? If not, the meshes might have been extracted by an older https://github.com/bast/MRI-extract-surfaces/

**Comment by bast** [comment] 2024-07-05 15:10
I will close this one but let's reopen if the issue is still here. Now the mesh directory also contains version information so then I can more easily correlate it with code changes.

**Closed as completed by bast** 2024-07-05 15:10 UTC
