### ISSUE TITLE
Error running TMS location

### ISSUE THREAD

**Issue by peraslaksen** [bast/tms-location#4] opened 2024-06-06 21:26 UTC
per@per-HP-EliteBook-850-G1:~/bast/tms-location-main$ ./tms-location.sif /home/per/bast/out
Traceback (most recent call last):
  File "/software/app.py", line 101, in <module>
    solver = create_solver(points, vertices)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/geodesic.py", line 8, in create_solver
    return pp3d.EdgeFlipGeodesicSolver(vertices, faces)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/venv/lib/python3.11/site-packages/potpourri3d/mesh.py", line 64, in __init__
    self.bound_solver = pp3db.EdgeFlipGeodesicsManager(V, F)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: GC_SAFETY_ASSERT FAILURE from /project/deps/geometry-central/src/surface/manifold_surface_mesh.cpp:109 - duplicate edge in list 19500 -- 9443

**Comment by bast** [comment] 2024-06-14 08:15
The meshes might have been generated by an older version of https://github.com/bast/MRI-extract-surfaces/. But if not, then this is a real problem that I know how to fix in the pre-processing step (but I thought I fixed this already).

I will add version info to the mesh folder so that we always know which version generated them.

**Comment by bast** [comment] 2024-07-05 15:09
I will close this one but let's reopen if the issue is still here. Now the mesh directory also contains version information so then I can more easily correlate it with code changes.

**Closed as completed by bast** 2024-07-05 15:09 UTC
